version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
